### ISSUE TITLE
LH TODO Tracker

### ISSUE THREAD

**Issue by Zethson** [schillerlab/sc-containers#1]
- [x] Add copy of environment.yml and install all packages & enable conda environment
- [x] Versionize the containers by putting them into folders
- [ ] Build containers automatically evaluate GHCR vs Quay vs Dockerhub
- [ ] Build documentation on GH Pages
- [ ] Discuss with team what the initial container should look like
- [ ] Maybe run the start.sh script by default when the container is started
- [ ] Add a cookiecutter version to quickly create new projects
